# Generated by Django 4.0.3 on 2022-03-25 20:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_event_timestamp_cannot_be_future_dated_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='event_timestamp_cannot_be_future_dated',
        ),
        migrations.AlterField(
            model_name='session',
            name='id',
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        'timestamp__lte',
                        datetime.datetime(2022, 3, 25, 20, 37, 24, 951867, tzinfo=utc),
                    )
                ),
                name='event_timestamp_cannot_be_future_dated',
            ),
        ),
    ]
