version: "3.9"

services:
  postgres:
    environment: &dbenv
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:12.9
    networks:
      - theeye
    ports:
      - "5432:5432"
  theeye:
    build: .
    command: bash
    environment:
      <<: *dbenv
      ALLOWED_HOSTS: '*'
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      DJANGO_SETTINGS_MODULE: the_eye.local_settings
      DEBUG: ${DEBUG}
      ENVIRONMENT: ${ENVIRONMENT}
      PYTHONUNBUFFERED: 1
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - postgres
    networks:
      - theeye
    ports:
      - "8001:8001"
    tty: true
    volumes:
      - .:/var/task:delegated
  celery:
    build: .
    environment:
      <<: *dbenv
      ALLOWED_HOSTS: '*'
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      DJANGO_SETTINGS_MODULE: the_eye.local_settings
      DEBUG: ${DEBUG}
      ENVIRONMENT: ${ENVIRONMENT}
      PYTHONUNBUFFERED: 1
    depends_on:
      - theeye
      - rabbitmq
    networks:
      - theeye
    volumes:
      - .:/var/task:delegated
    command: celery -A the_eye worker --events --without-gossip --without-mingle --without-heartbeat -l debug
  rabbitmq:
    image: rabbitmq:3.9.14-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    networks:
      - theeye

networks:
  theeye:
